### PR TITLE
Duo on Date bug fixed if no cycle selected

### LINKED ISSUE #981: TypeError: this.dueOnDate.toISOString When adding assignee to task. but not when changing Due On
### Your environment:
Ubuntu, Fresh install from master

### Description:
when editing a task when adding assignee I get a javascript error when I hit save.  I do not get the error when I only change the Due On Field. 

vendor.min.js:1 TypeError: this.dueOnDate.toISOString is not a function
    at a.updateTask (home.min.js?id=4afa70550949e85515db:1)
    at Ue (vendor.min.js:1)
    at HTMLButtonElement.n (vendor.min.js:1)
    at HTMLButtonElement.Jr.o._wrapper (vendor.min.js:1)

### Steps To Reproduce:

Edit a task that does not have an assignee and try to add one. 
image

### PR DESCRIPTION
**Pull request by Rafatlne**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [ ] Check you have added tests that prove your fix is effective or that your feature works.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Due on date bug fixed if no cycle selected.
This closes #981 and #965

💔Thank you!

### CODE REVIEW

File: resources/assets/js/components/forms/createTaskForm.vue [hunk 1]
```diff
@@ -321,6 +323,13 @@ export default {
       
       this.editedFirstTask =  false
 
+    },
+    updateDueOnDate(edited_dueDate){
+      if(edited_dueDate !== null && edited_dueDate !== '') {
```
Comment (Rafatlne) [inline resources/assets/js/components/forms/createTaskForm.vue:328]: this has some issue

File: resources/assets/js/components/forms/createTaskForm.vue [hunk 2]
```diff
@@ -325,7 +325,8 @@ export default {
 
     },
     updateDueOnDate(edited_dueDate){
-      if(edited_dueDate !== null && edited_dueDate !== '') {
+      let tempDate = window.luxon.DateTime.fromISO(edited_dueDate).toISODate()
```
Comment (Rafatlne) [inline resources/assets/js/components/forms/createTaskForm.vue:328]: @Hasnayeen i only added code here.
